version: "3"

services:
  app:
    build: .
    image: url-parser
    container_name: url-parser-app
    command: "rake dev_up test_up"
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      RACK_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: db
    volumes: &web-volumes
      - ./:/app
      - ~/.bash_history:/root/.bash_history

  db:
    image: postgres:12-alpine
    container_name: url-parser-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_MULTIPLE_DATABASES: app,app_test
    volumes:
      - .pg_data:/var/lib/postgresql/data
      - ./etc/db/:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:5432:5432"

